# Generated by Django 4.2.6 on 2023-10-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_deliveryfirstname_customeruser_customfirstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.publishing'),
        ),
    ]
