# Generated by Django 3.2.23 on 2023-11-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cityname',
        ),
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.city', verbose_name='Город'),
        ),
    ]
