# Generated by Django 4.2.5 on 2023-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cityname',
        ),
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='streetname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.street'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
