# Generated by Django 4.2.5 on 2023-11-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0010_remove_address_cityname_street_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='toaddress',
            new_name='to_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arrivaldate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='countofbook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerusers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryusers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departuredate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='Deliveryuser',
        ),
        migrations.DeleteModel(
            name='Orderstatus',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.order'),
        ),
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(through='book.OrderBook', to='book.book'),
        ),
    ]
