# Generated by Django 4.2.5 on 2023-11-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_orderbook_rename_toaddress_order_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
