# Generated by Django 4.2.5 on 2023-11-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оплата')),
                ('summa', models.FloatField(verbose_name='Сумма')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.usercard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Paymentstatus',
        ),
    ]
