# Generated by Django 4.2.5 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_payment_delete_card_delete_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='cardyear',
        ),
        migrations.AlterField(
            model_name='usercard',
            name='dateissue',
            field=models.CharField(max_length=4, verbose_name='Дата истечения'),
        ),
    ]
