# Generated by Django 4.2.5 on 2023-11-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_usercard_cardyear_alter_usercard_dateissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='cardholder',
        ),
        migrations.DeleteModel(
            name='Cardholder',
        ),
    ]
